name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'tag(latest or x.x.x)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.step1.check-tags.tags }}
    steps:
      - id: check-tags
        run: |
          if [[ ${{ github.event.inputs.repository }} == "latest" ]]; then
            echo "tags=nobodyiam/apollo-quick-start:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=nobodyiam/apollo-quick-start:latest,nobodyiam/apollo-quick-start:${{ github.event.inputs.repository }}" >> $GITHUB_OUTPUT
          fi
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nobodyiam
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: nobodyiam/apollo-quick-start:${{ needs.build.outputs.tags }}
